apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-openshift-builds/catalog?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" &&
      target_branch == "main" &&
      (
        files.all.exists(x, x.matches('fbc/4.17')) ||
        files.all.exists(x, x.matches('.tekton/openshift-builds-fbc-4-17-push.yaml'))
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: openshift-builds-fbc-4-17
    appstudio.openshift.io/component: openshift-builds-fbc-4-17
    pipelines.appstudio.openshift.io/type: build
  name: openshift-builds-fbc-4-17-on-push
  namespace: rh-openshift-builds-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds-fbc-4-17:{{revision}}
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: fbc/4.17
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/redhat-openshift-builds/release.git
      - name: revision
        value: main
      - name: pathInRepo
        value: /pipelines/konflux-build-fbc.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-openshift-builds-fbc-4-17
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}

